# Generated by Django 5.2 on 2025-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='source',
        ),
        migrations.AddField(
            model_name='feedback',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('sofa_set', 'Sofa Set'), ('dining_sets', 'Dining Sets'), ('console_cabinet_coffee', 'Console/Cabinet/Coffee Table'), ('bedroom_sets', 'Bedroom Sets'), ('accessories', 'Accessories'), ('mattresses', 'Mattresses'), ('office_chairs', 'Office Chairs'), ('office_tables', 'Office Tables'), ('workstations', 'Workstations'), ('filing_cabinets', 'Filing Cabinets'), ('safes', 'Safes'), ('link_chairs', 'Link Chairs'), ('office_sofas', 'Office Sofas'), ('reception_desks', 'Reception Desks'), ('customization', 'Customization')], default='sofa_set', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='deal_worth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='how_did_you_hear',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('influencers', 'Influencers'), ('outdoor_media', 'Outdoor Media'), ('newsletter', 'Newsletter/Email'), ('word_of_mouth', 'Word of Mouth'), ('sms', 'SMS'), ('repeat_customer', 'Repeat Customer')], default='social_media', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='interested_in',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='quotation_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sale_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='specific_products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
