# Generated by Django 5.2 on 2025-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_source_feedback_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer_name',
            field=models.CharField(default='Name', max_length=255),
        ),
    ]
