# Generated by Django 5.2 on 2025-04-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='specific_products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
